### ISSUE TITLE
possible memory leaks?

### ISSUE THREAD

**Issue by Xudong-Huang** [XiangpengHao/congee#17]
Thanks for this greate lib. But when I run bench, I saw a huge memory usage on my computer. I have 48GB memory, and it corrupts when memory is not enough.

```
env SHUMAI_FILTER="InsertOnly-ART" RUSTFLAGS='-C target-cpu=native' cargo bench --bench basic

============================================================
Running benchmark for 3 seconds with 32 threads: basic-basic-InsertOnly-ART
error: bench failed, to rerun pass `--bench basic`

Caused by:
  process didn't exit successfully: `/home/huang/project/rust/congee/target/release/deps/basic-5809d0889700a950 --bench` (signal: 9, SIGKILL: kill)
```

How many memory should I have to run this bench?

**Comment by XiangpengHao** [comment]
Hi @Xudong-Huang , thank you for your interests in congee! I did not find obvious memory leak using memory sanitizer:
```bash
env RUSTFLAGS="-Zsanitizer=memory" cargo test -Zbuild-std --target x86_64-unknown-linux-gnu --tests
```

But I can reproduce the OOM error on my own machine with 32GB memory and can successfully run on a machine with 196GB memory.

The nature of insert-only workload means that the data structure grows continuously, and the more time it runs, the more memory it consumes.

One way to finish the benchmark on a relatively small machine is to limit the thread count or time in the `bench/benchmark.toml` file.

```toml
[[Basic]]
name = "test"
threads = [8] <----- change to a lower thread count
time = 3 <----- or shorter time
workload = ["ReadOnly", "InsertOnly", "UpdateOnly", "ScanOnly"]
index_type = ["ART"]
``` 

And then run:
```bash
env SHUMAI_FILTER="test" RUSTFLAGS='-C target-cpu=native' cargo bench --bench basic 
```

**Comment by Xudong-Huang** [comment]
Thanks. That make sense.
