### ISSUE TITLE
add is_empty API

### ISSUE THREAD

**Issue by Xudong-Huang** [XiangpengHao/congee#18]
is it possible to support is_empty API?
```rust
pub fn is_empty(&self)
```

**Comment by XiangpengHao** [comment]
`is_empty()` as well as `len()` are high level APIs, here's why:

- Let's consider we use an atomic variable to count the number of values in the data structure, on most platforms the atomic variable can perform 5-10M operations (e.g., fetch add) per second.
- Congee is designed to support more than 50M insertions per second, effectively been bottlenecked by a global atomic counter
- We can alleviate this by sharding the data or having multiple counters etc, but they are not without overheads.

But I agree that a less user-hostile API is needed for most people that don't need this level of performance. I'll try to hack a wrapper on top of current congee later this week and let you know if I find anything...

cc @WetABQ who might also be interested

**Comment by Xudong-Huang** [comment]
The `len()` API is not that needed for a concurrent data structure. But `is_empty()` could do some quick check in some senarios.
Also, `is_empty()` can be implemented by simply quick check the root node.

**Comment by XiangpengHao** [comment]
you're absolutely right -- added

**Comment by Xudong-Huang** [comment]
Thanks!
