### ISSUE TITLE
add drain API

### ISSUE THREAD

**Issue by Xudong-Huang** [XiangpengHao/congee#19]
since the value type can't be arbitray, we could use a pointer for the value, but this need to free the memory in drop.

the drain API takes a mutable ref, we are sure that there is no shared contention.

**Comment by XiangpengHao** [comment]
Added! Thank you for the suggestion! Congee now supports `new_with_drainer` which calls the drainer function on every value that is about to drop.


https://github.com/XiangpengHao/congee/blob/93aa5ed444f06f4b39e14c620ee0ea294fa057a9/src/lib.rs#L205-L241

**Comment by Xudong-Huang** [comment]
Wonderful!
